### ISSUE TITLE
Doesn't recognize `tel:` uris

### ISSUE THREAD

**Issue by Iiridayn** [moinwiki/moin-1.9#34]
## Tried:

(actual number obscurified)

`[[tel:1234567890|123-456-7890]]`

## Got:

`<a class="nonexistent" href="/tel%3A1234567890">123-456-7890</a>`

## Expected:

`<a class="tel" href="tel:1234567890">123-456-7890</a>`

**Comment by esyr-rh** [comment]
That is usually worked around by adding something like " tel tel:" to a local InterWikiMap.

**Comment by ThomasWaldmann** [comment]
https://github.com/moinwiki/moin-1.9/blob/master/MoinMoin/config/__init__.py#L85 no "tel" there (yet).

**Comment by ThomasWaldmann** [comment]
https://github.com/moinwiki/moin-1.9/commit/4bf60d4d46eaa15d29293385f3e30971b3223a49 fixed.
