### ISSUE TITLE
pip install moin crash when ascii codec in setup.cfg

### ISSUE THREAD

**Issue by raimonesteve** [moinwiki/moin-1.9#40]
`pip install moin`

```
 Using cached https://files.pythonhosted.org/packages/db/c4/58872c31f3c242c2cec3a35f493628182979b664645858dafba4071b9cb5/moin-1.9.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9h3pHq/moin/setup.py", line 355, in <module>
        setup(**setup_args)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/tmp/prova/local/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
        self._parse_config_files(filenames=filenames)
      File "/tmp/prova/local/lib/python2.7/site-packages/setuptools/dist.py", line 599, in _parse_config_files
        (parser.read_file if six.PY3 else parser.readfp)(reader)
      File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
        self._read(fp, filename)
      File "/usr/lib/python2.7/ConfigParser.py", line 481, in _read
        line = fp.readline()
      File "/tmp/prova/lib/python2.7/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 57: ordinal not in range(128)
```

The reason is that setup.cfg there are some characters can't codec: "Jürgen"

Finally I download from source code and done with:

`moin-1.9$ python setup.py install`

**Comment by ThomasWaldmann** [comment]
Try:

```
$ LANG=C.ISO-8859-1 pip install moin
```

I could reproduce the problem on a fresh and relatively minimal system and test that "fix".

But I don't remember ever needing this before, so the question is what has changed. All moin versions of the last years produced the problem when installing with pip. I also tried older pip versions, same thing.

**Comment by raimonesteve** [comment]
The problem is that recent pip versions read setup.cfg and can not contain utf8.

Other projects remove some accents to setup.cfg because can not contain utf8. Exemple [1]

[1] https://github.com/dune-community/dune-xt-common/commit/8451b54989d984a8139d8f4621a68aa87a1687a6

Note:
Also my second name has some accents: "Cusiné" ;)

**Comment by ThomasWaldmann** [comment]
In my experiment I downgraded pip until version < 9 and it still happened.

**Comment by ThomasWaldmann** [comment]
TODO for 1.9.11: play safe and remove all non-ascii stuff from setup.cfg and setup.py.

**Comment by delocalizer** [comment]
Just a comment - the actual issue here was not accents or non-ascii characters _per se_ in  setup.cfg, but the encoding of the file, which was ISO-8859-1. Recent versions of distutils (called by `pip install`) require that setup.cfg be encoded in UTF-8, see e.g. https://github.com/pypa/setuptools/issues/1702. So if you like you can have `Jürgen` in setup.cfg but just make sure the file is encoded as UTF-8.

You can check the encoding on a Linux system with `file setup.cfg` and convert between encodings on the command-line using `iconv`, e.g.
```
iconv -f ISO-8859-1 -t UTF-8 old/setup.cfg > new/setup.cfg
```

**Comment by ThomasWaldmann** [comment]
@delocalizer thanks for the hint, but I guess I just prefer pure ASCII to avoid any issues in there.
