### ISSUE TITLE
Edit in GUI - CKeditor instead of FCKeditor dependency

### ISSUE THREAD

**Issue by svelsae** [moinwiki/moin-1.9#43]
Dear MoinMoin Team,

I use MoinWiki on Ubuntu 18.04 and just had to the issue mentioned on:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784327

Since FCKeditor is not longer developed, is there a recommended upgrade path to use CKeditor?

Best Regards

Sven

**Comment by ThomasWaldmann** [comment]
The default (and recommended) configuration has the gui editor disabled.

There is no upgrade path to CKeditor (in general, moin 1.9.x is not getting any new features).
