### ISSUE TITLE
Moin + Apache over NFS

### ISSUE THREAD

**Issue by robertosussex** [moinwiki/moin-1.9#80]
Hi,

I have noticed that while
**moin 1.9.10 + Apache 2.2.15 + Centos 6.10**
works with data_dir and underlay mounted over NFS
**moin1.9.11 + Apache 2.4.6 + Centos 7.9.2009**
does not
![image](https://user-images.githubusercontent.com/37402138/120485475-0aec9480-c3ac-11eb-8ec7-3d3642ae9ee9.png)
It gives 500 Internal error and in the logs

[Wed Jun 02 14:03:13.458126 2021] [:error] [pid 11713] 2021-06-02 14:03:13,458 INFO MoinMoin.config.multiconfig:127 using wiki config: /etc/moin/epp.py
[Wed Jun 02 14:03:16.253860 2021] [:error] [pid 11713] 2021-06-02 14:03:16,252 ERROR MoinMoin.wsgiapp:281 An exception has occurred [http://epp-wiki.hpc.susx.ac.uk/].
[Wed Jun 02 14:03:16.253910 2021] [:error] [pid 11713] Traceback (most recent call last):
[Wed Jun 02 14:03:16.253915 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/wsgiapp.py", line 264, in __call__
[Wed Jun 02 14:03:16.253917 2021] [:error] [pid 11713]     response = run(context)
[Wed Jun 02 14:03:16.253919 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/wsgiapp.py", line 89, in run
[Wed Jun 02 14:03:16.253921 2021] [:error] [pid 11713]     response = dispatch(request, context, action_name)
[Wed Jun 02 14:03:16.253923 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/wsgiapp.py", line 137, in dispatch
[Wed Jun 02 14:03:16.253925 2021] [:error] [pid 11713]     response = handle_action(context, pagename, action_name)
[Wed Jun 02 14:03:16.253927 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/wsgiapp.py", line 203, in handle_action
[Wed Jun 02 14:03:16.253929 2021] [:error] [pid 11713]     handler(context.page.page_name, context)
[Wed Jun 02 14:03:16.253931 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/action/__init__.py", line 267, in do_show
[Wed Jun 02 14:03:16.253933 2021] [:error] [pid 11713]     content_only=content_only,
[Wed Jun 02 14:03:16.253935 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/Page.py", line 1332, in send_page
[Wed Jun 02 14:03:16.253937 2021] [:error] [pid 11713]     start_line=pi['lines'])
[Wed Jun 02 14:03:16.253939 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/Page.py", line 1426, in send_page_content
[Wed Jun 02 14:03:16.253941 2021] [:error] [pid 11713]     self.execute(request, parser, code)
[Wed Jun 02 14:03:16.253943 2021] [:error] [pid 11713]   File "/usr/lib64/pypy-5.0.1/site-packages/MoinMoin/Page.py", line 1457, in execute
[Wed Jun 02 14:03:16.253945 2021] [:error] [pid 11713]     exec code
[Wed Jun 02 14:03:16.253947 2021] [:error] [pid 11713]   File "EPP", line 2, in <module>
[Wed Jun 02 14:03:16.253949 2021] [:error] [pid 11713] TypeError: 'dict' object is not callable
[Wed Jun 02 14:03:16.254023 2021] [:error] [pid 11713] [remote 54.209.62.75:144] mod_wsgi (pid=11713): Exception occurred processing WSGI script '/usr/lib64/pypy-5.0.1/share/moin/server/moin.wsgi'.
[Wed Jun 02 14:03:16.254049 2021] [:error] [pid 11713] [remote 54.209.62.75:144] Traceback (most recent call last):

.....
.....

===============
Same data copied locally works perfectly!!

**Comment by ThomasWaldmann** [comment]
try cleaning the cache (something like "moin maint cleancache" plus giving url / config).

**Comment by robertosussex** [comment]
Confirmed! It does work indeed. I think I have seen this before I had forgotten about it :-)
Many thanks anyway
Roberto
