### ISSUE TITLE
htaccess file with some local stuff found

### ISSUE THREAD

**Issue by bossjl** [moinwiki/moin-1.9#82]
Hello,

I found this htaccess file with some local references in the FCKeditor, might not be a security issue, but i think it could be removed:

./MoinMoin/web/static/htdocs/applets/FCKeditor/editor/filemanager/connectors/py/htaccess.txt:PythonPath "[r'C:\Archivos de programa\Apache Software Foundation\Apache2.2\htdocs\fckeditor\editor\filemanager\connectors\py'] + sys.path"

Regards and thanks for your work.

**Comment by ThomasWaldmann** [comment]
This is part of the fckeditor project files which we just bundled - we are neither developing nor "fixing" these.

Also, IIRC, we do not use the "filemanager" feature and usage of fckeditor in general is rather discouraged due to its age.
